### ISSUE TITLE
How to apply patch?

### ISSUE THREAD

**Issue by donhollen** [kkujawinski/sublime-text-3-patch-apply#1]
Sorry, new to sublime text plugins.

I've chosen Package Control: Apply Repository
Pasted the .git URL and hit ENTER
Closed and re-opened Sublime Text

Now how do i apply a patch?  Or, what step did i miss?

**Comment by kkujawinski** [comment]
Hi,

Quick Apply
1. `ctrl` + `shift` + `p`
2. `Patch apply: Quick apply`
3. Paste patch in to new tab
4. Close tab
5. Select root directory  where it should be applied
6. Done

Full Apply
1. `ctrl` + `shift` + `p`
2. `Patch apply: Apply`
3. Paste patch in to new tab
4. Close tab
5. Select root directory where it should be applied
6. Provide `-p` parameter for patch command
7. Done

**Comment by donhollen** [comment]
Thank you mucho!
